### PR TITLE
Moving `#[Route()]` attribute upwards

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Due to https://stackoverflow.com/a/74678367/1668200

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the improvement. I think this might take few years before it becomes mainstream. It's really confusing as it is now, and we try to stick with most common context for the common fw/PHP versions.

Maybe we can revisit in 6-12 months. Thanks for understanding

**Comment by ThomasLandauer** [comment]
Yeah, closing this is OK. But what's the advantage of invokable controllers at all? Why are you advocating them?

**Comment by TomasVotruba** [comment]
For example these 2:

* https://tomasvotruba.com/blog/2020/12/21/5-new-combos-opened-by-symfony-52-and-php-80/
* https://tomasvotruba.com/blog/to-route-or-to-action-thats-the-question

**Comment by ThomasLandauer** [comment]
Yeah, thanks, the Laravel post convinced me :-) I suggested it for Symfony too: https://github.com/symfony/symfony/issues/49981

**Pull request closed without merging**
