### PR TITLE
nette/utils 4.0

### PR DESCRIPTION
**Pull request by enumag**
Same thing as earlier for tomasvotruba/type-coverage. Let's check first if nothing fails with 4.0 and allow both if it's fine.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Using directly 3.4|4.0 will save me from one more check here :)
Composer always install the latest version, so it's checked by default

**Comment by enumag** [comment]
@TomasVotruba not necessarily... if there was another dependency in the chain with requirement to nette/utils 3 then composer would resolve it to 3 and we wouldn't learn about a potential error with v4. And as it happens this is exactly the case - `symplify/rule-doc-generator-contracts` requires `nette/utils` 3.

**Comment by TomasVotruba** [comment]
You can test this quickly locally and get here with results :+1:

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Pull request merged**
