### PR TITLE
Fixing typo

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Closes https://github.com/symplify/phpstan-rules/issues/28

### CODE REVIEW

**Comment by TomasVotruba** [comment]
CI needs fixing first

**Comment by ThomasLandauer** [comment]
Sorry, I don't know how to rename the directory :-(

**Comment by ThomasLandauer** [comment]
I'm doing it on GitHub's website ;-) Could you take care of the rest, please?

**Comment by TomasVotruba** [comment]
Ah, better use normal git :)  web is good only for single changes.
I'm focused on other work now.

**Pull request closed without merging**
